data:
  source_path: data/salary_dataset.csv     # ✅ Add this if missing
  raw_path: data/raw                       # ✅ Add this if missing
  train_path: data/raw/train.csv
  test_path: data/raw/test.csv
  target: salary

features:
  num_cols:
    - experience
    - age
    - projects_completed
    - hours_per_week
  cat_cols:
    - job_role
    - education_level
    - location

split:
  test_size: 0.2
  random_state: 42

model:
  output_path: models/model.pkl
  n_estimators: 100
  max_depth: 10
  min_samples_split: 5
  min_samples_leaf: 3
  n_jobs: -1

evaluation:
  metrics_output: metrics.json
